# docker-compose.yml
version: '3.1'
services:
  postgres-db:
    image: postgres:11-alpine
    restart: always
    container_name: postgres-db-craftsoft
    environment:
      POSTGRES_PASSWORD: Craftsoft_Strong_Password???1!1
      POSTGRES_DB: craftsoft_cdr
      POSTGRES_USER: craftsoft
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: